version: '3.5'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - PORT=3005
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://cache
      - CLIENT_ID=3ce9a417f2094431888205c85f2e61a8
      - CLIENT_SECRET=2b69ce3f0d3643d0a65f8537c490e775
    ports:
      - "3005:3005"
    depends_on:
      - db
      - cache
    volumes:
      - ./:/app

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - music-data:/data/db
    ports:
      - "27017:27017"

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    volumes:
      - cache:/data
    expose:
      - 6379

volumes:
  music-data:
    driver: local
  cache:
    driver: local
