version: '3.5'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    environment:
      - PORT=3005
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://cache
      - CLIENT_ID=2fc61d1ba61047b993648497ee507b66
      - CLIENT_SECRET=166e2d172b85484d883d62052cb69756
      - PASS=h3ll0
    ports:
      - "3005:3005"
    depends_on:
      - db
      - cache

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - music-data:/data/db
    ports:
      - "27017:27017"

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    expose:
      - 6379

volumes:
  music-data:
